M48
; DRILL file {KiCad 7.0.8} date Sun Mar 10 19:24:47 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-10T19:24:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X111.0Y-27.0
X111.0Y-141.0
X207.25Y-27.0
X207.25Y-141.0
T0
M30
